title: Moleculize
email: ms.rachel.mann@gmail.com
description: >
  The "Angry Birds" of synthetic biology
baseurl: ""
url: "http://moleculyze.github.io"
twitter_username: biofille
github_username:  biofille

# Build settings
markdown: kramdown
